export const SESSION_COOKIE = 'ziftlab-admin-session'
export const TWO_FACTOR_CHALLENGE_COOKIE = 'ziftlab-admin-2fa-challenge'
export const MUST_CHANGE_PASSWORD_COOKIE = 'ziftlab-admin-must-change-password'
export const MUST_SETUP_2FA_COOKIE = 'ziftlab-admin-must-setup-2fa'
export const DASHBOARD_PATH = '/dashboard'
