#!/usr/bin/env bash
# Generate development environment files for GitHub Codespaces.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

codespace_url() {
  local port="$1"

  if [ -n "${CODESPACE_NAME:-}" ] && [ -n "${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN:-}" ]; then
    printf 'https://%s-%s.%s' "$CODESPACE_NAME" "$port" "$GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN"
  else
    printf 'http://app:%s' "$port"
  fi
}

existing_value() {
  local file="$1"
  local key="$2"

  if [ -f "$file" ]; then
    grep -E "^${key}=" "$file" | head -n 1 | cut -d= -f2- || true
  fi
}

random_hex() {
  node -e "console.log(require('crypto').randomBytes(32).toString('hex'))"
}

ADMIN_PUBLIC_URL="${ADMIN_PUBLIC_URL:-$(codespace_url 3000)}"
WEB_PUBLIC_URL="${WEB_PUBLIC_URL:-$(codespace_url 4321)}"
ADMIN_DATABASE_URL_VALUE="${ADMIN_DATABASE_URL:-postgresql://postgres:postgres@postgres:5432/ziftlab_admin_dev}"
INTERNAL_API_URL_VALUE="${INTERNAL_API_URL:-http://app:3000}"
INTERNAL_CONTENT_API_URL_VALUE="${INTERNAL_CONTENT_API_URL:-$INTERNAL_API_URL_VALUE}"
ADMIN_BOOTSTRAP_TOKEN_VALUE="${ADMIN_BOOTSTRAP_TOKEN:-$(existing_value admin/.env ADMIN_BOOTSTRAP_TOKEN)}"
ADMIN_CSRF_SECRET_VALUE="${ADMIN_CSRF_SECRET:-$(existing_value admin/.env ADMIN_CSRF_SECRET)}"
ADMIN_TOTP_ENCRYPTION_KEY_VALUE="${ADMIN_TOTP_ENCRYPTION_KEY:-$(existing_value admin/.env ADMIN_TOTP_ENCRYPTION_KEY)}"

if [ -z "$ADMIN_BOOTSTRAP_TOKEN_VALUE" ]; then
  ADMIN_BOOTSTRAP_TOKEN_VALUE="$(random_hex)"
fi

if [ -z "$ADMIN_CSRF_SECRET_VALUE" ]; then
  ADMIN_CSRF_SECRET_VALUE="$(random_hex)"
fi

if [ -z "$ADMIN_TOTP_ENCRYPTION_KEY_VALUE" ]; then
  ADMIN_TOTP_ENCRYPTION_KEY_VALUE="$(random_hex)"
fi

cat > .env <<ENV
# Generated for GitHub Codespaces. Do not commit real secrets.
NODE_ENV=development
ADMIN_APP_URL=$ADMIN_PUBLIC_URL
ADMIN_ALLOWED_ORIGINS=$ADMIN_PUBLIC_URL,$WEB_PUBLIC_URL
ADMIN_DATABASE_URL=$ADMIN_DATABASE_URL_VALUE
INTERNAL_API_URL=$INTERNAL_API_URL_VALUE
INTERNAL_CONTENT_API_URL=$INTERNAL_CONTENT_API_URL_VALUE
PUBLIC_SITE_URL=$WEB_PUBLIC_URL
PUBLIC_API_URL=
PUBLIC_CONTENT_API_URL=
PUBLIC_ANALYTICS_ENABLED=true
S3_ENDPOINT=http://minio:9000
S3_REGION=us-east-1
S3_BUCKET=ziftlab-media
S3_ACCESS_KEY_ID=minioadmin
S3_SECRET_ACCESS_KEY=minioadmin
S3_FORCE_PATH_STYLE=true
S3_PREFIX=admin-media
S3_PUBLIC_BASE_URL=
ENV

cat > admin/.env <<ENV
# Generated for GitHub Codespaces. Do not commit real secrets.
NODE_ENV=development
ADMIN_APP_URL=$ADMIN_PUBLIC_URL
ADMIN_ROUTE_GUARD=true
ADMIN_BOOTSTRAP_TOKEN=$ADMIN_BOOTSTRAP_TOKEN_VALUE
ADMIN_DATABASE_URL=$ADMIN_DATABASE_URL_VALUE
ADMIN_SESSION_DAYS=14
ADMIN_SESSION_IDLE_MINUTES=120
ADMIN_LOGIN_MAX_ATTEMPTS=5
ADMIN_LOGIN_WINDOW_MINUTES=15
ADMIN_LOGIN_LOCK_MINUTES=15
ADMIN_IP_MAX_FAILED_ATTEMPTS=10
ADMIN_IP_WINDOW_MINUTES=15
ADMIN_IP_BLOCK_MINUTES=60
ADMIN_PASSWORD_MIN_LENGTH=12
ADMIN_ARGON2_MEMORY=65536
ADMIN_ARGON2_TIME=3
ADMIN_ARGON2_PARALLELISM=1
ADMIN_TOTP_ISSUER=ZiftLab
ADMIN_TOTP_ENCRYPTION_KEY=$ADMIN_TOTP_ENCRYPTION_KEY_VALUE
ADMIN_2FA_CHALLENGE_MINUTES=5
ADMIN_ENFORCE_2FA_FOR_SENSITIVE=true
ADMIN_CSRF_SECRET=$ADMIN_CSRF_SECRET_VALUE
ADMIN_ALLOWED_ORIGINS=$ADMIN_PUBLIC_URL,$WEB_PUBLIC_URL
ADMIN_PREVIEW_TOKEN=
BACKUP_S3_PREFIX=admin-backups
BACKUP_AUTO_ENABLED=false
BACKUP_AUTO_CRON=0 3 * * *
BACKUP_CRON_SECRET=
BACKUP_RETENTION_DAYS=30
LEADS_NOTIFY_EMAILS=
RESEND_FROM_EMAIL=
LEADS_CRM_WEBHOOK_URL=
LEADS_CRM_WEBHOOK_SECRET=
LEADS_CRM_AUTO_SEND=false
PUBLIC_SITE_URL=$WEB_PUBLIC_URL
PUBLIC_ANALYTICS_ENABLED=true
ANALYTICS_EVENT_SALT=
S3_ENDPOINT=http://minio:9000
S3_REGION=us-east-1
S3_BUCKET=ziftlab-media
S3_ACCESS_KEY_ID=minioadmin
S3_SECRET_ACCESS_KEY=minioadmin
S3_FORCE_PATH_STYLE=true
S3_PREFIX=admin-media
S3_PUBLIC_BASE_URL=
ENV

cat > web/.env <<ENV
# Generated for GitHub Codespaces. Do not commit real secrets.
PUBLIC_SITE_URL=$WEB_PUBLIC_URL
PUBLIC_API_URL=
PUBLIC_CONTENT_API_URL=
INTERNAL_API_URL=$INTERNAL_API_URL_VALUE
INTERNAL_CONTENT_API_URL=$INTERNAL_CONTENT_API_URL_VALUE
PUBLIC_ANALYTICS_ENABLED=true
PUBLIC_GA4_ID=
PUBLIC_GTM_CONTAINER_ID=
PUBLIC_CLARITY_ID=
PUBLIC_META_PIXEL_ID=
PUBLIC_HOTJAR_ID=
PUBLIC_GOOGLE_ADS_ID=
ENV

cat > packages/db/.env <<ENV
# Generated for GitHub Codespaces. Do not commit real secrets.
ADMIN_DATABASE_URL=$ADMIN_DATABASE_URL_VALUE
ENV

echo "Codespaces env files generated."
echo "Web:       $WEB_PUBLIC_URL"
echo "Dashboard: $ADMIN_PUBLIC_URL/dashboard"
